version: '2'
services:
  oice-nginx:
    image: nginx:latest
    ports:
     - "80:80"
    links:
     - oice-server:oice-server
     - oice-socket:oice-socket
     - oice-web:oice-web
    volumes:
     - ./upload:/upload
     - ./view:/view
     - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/conf/oice.conf:/etc/nginx/oice.conf:ro
  oice-db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=modmod
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
  oice-server:
    build: ./oice-server
    image: modmod:latest
    command: pserve example.ini
    ports:
     - "6543:6543"
    links:
     - oice-db:oice-db
     - redis
    volumes:
     - ./upload:/upload
     - ./view:/view
  oice-socket:
    build: ./oice-server/socket.io
    ports:
     - "8082:8082"
  oice-worker:
    build: ./rqworker
    links:
     - oice-socket:oice-socket
     - oice-db:oice-db
    environment:
     - MODMOD_SOCKETIO_HOST=oice-socket
    volumes:
     - ./upload:/upload
     - ./view:/view
    depends_on:
    - redis
    - oice-server
  oice-web:
    build:
      context: ./oice-web
      dockerfile: Dockerfile.Dev
      args:
        - SRV_ENV=127.0.0.1
        - NODE_ENV=DEBUG
    command: yarn start
    volumes:
      - ./oice-web/src:/app/src
    ports:
     - "3000:3000"
